logging:
  level: info
  timestamp: 'YYYY-MM-DD HH:mm:ss'
web:
  hostname: localhost
  port: 3000
  tokens:
    age: 3600 # one hour
    secret: changeme
database:
  host: localhost
  port: 27017
  user: gusta
  password: changeme
  database: gusta
