version: '3'
services:
  api:
    build: .
    container_name: flavor-api
    environment:
      - FLAVOR_API_JWT_SECRET=changeme
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=gusta
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
